name: joshbeute
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9986311150714755
title: joshbeute
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72193151-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.10904156160540879
  lightness: 0.753700140863657
  saturation: 0.25577985658310354
  rhythmicContrast: 0.8555607113521546
purpose: []
